---
- name: Refresh certificates
  command: microk8s refresh-certs
  become: true
- name: Reboot host
  reboot:
    msg: "Reboot initiated by Ansible"
    connect_timeout: 5
    reboot_timeout: 600
    pre_reboot_delay: 0
    post_reboot_delay: 30
    test_command: microk8s kubectl get nodes
  become: true