replicaCount: 1

image:
  repository: sebaczech/python-flask-api-hostname-env-time
  pullPolicy: Always
  tag: "1.0"

imagePullSecrets: []
nameOverride: "flask-api"
fullnameOverride: "flask-api-chart"

serviceAccount:
  create: true
  annotations: {}
  name: flask-api

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

app:
  port: 5080

service:
  type: NodePort
  port: 80

ingress:
  enabled: true
  className: ""
  annotations:
    kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  paths:
    - /
  hosts:
    - host: flask-api.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: flask-api-tls
  #    hosts:
  #      - flask-api.local

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
