---
- name: Get node public IP address
  uri:
    url: http://ifconfig.co
    return_content: yes
    headers:
      Accept: text/plain
  register: public_ip
- name: Configure IP addresses in certificates
  block:
  - name: Add node public IP as a SAN in certificate
    lineinfile:
      path: /var/snap/microk8s/current/certs/csr.conf.template
      regexp: "^IP.50 = .*"
      insertbefore: '^#MOREIPS'
      firstmatch: yes
      line: "IP.50 = {{ public_ip.content | trim }}"
    notify:
    - Refresh certificates
    - Reboot host
  - name: Add node private IP as a SAN in certificate
    lineinfile:
      path: /var/snap/microk8s/current/certs/csr.conf.template
      regexp: "^IP.60 = .*"
      insertbefore: '^#MOREIPS'
      firstmatch: yes
      line: "IP.60 = {{ ansible_facts['enp0s3']['ipv4']['address'] }}"
    notify:
    - Refresh certificates
    - Reboot host
  - name: Add LB public IP as a SAN in certificate
    lineinfile:
      path: /var/snap/microk8s/current/certs/csr.conf.template
      regexp: "^IP.70 = .*"
      insertbefore: '^#MOREIPS'
      firstmatch: yes
      line: "IP.70 = {{ lb_public_ip }}"
    notify:
    - Refresh certificates
    - Reboot host
  - name: Add the user ubuntu to group microk8s
    user:
      name: ubuntu
      groups: microk8s
      append: yes
  - name: Wait for snap to finish changes in progress
    command: snap changes
    register: snap_changes
    until: snap_changes.stdout.find("Doing") == -1
    retries: 6
    delay: 10
  - name: Flush handlers
    meta: flush_handlers
  become: true