---
- name: Get node public IP address
  uri:
    url: http://ifconfig.co
    return_content: yes
    headers:
      Accept: text/plain
  register: public_ip
- name: Configure IP address in certificate
  block:
  - name: Add node public IP as a SAN in certificate
    lineinfile:
      path: /var/snap/microk8s/current/certs/csr.conf.template
      regexp: "^IP.50 = .*"
      insertbefore: '^#MOREIPS'
      firstmatch: yes
      line: "IP.50 = {{ public_ip.content | trim }}"
  - name: Add node private IP as a SAN in certificate
    lineinfile:
      path: /var/snap/microk8s/current/certs/csr.conf.template
      regexp: "^IP.60 = .*"
      insertbefore: '^#MOREIPS'
      firstmatch: yes
      line: "IP.60 = {{ ansible_facts['enp0s3']['ipv4']['address'] }}"
  - name: Add LB public IP as a SAN in certificate
    lineinfile:
      path: /var/snap/microk8s/current/certs/csr.conf.template
      regexp: "^IP.70 = .*"
      insertbefore: '^#MOREIPS'
      firstmatch: yes
      line: "IP.70 = {{ lb_public_ip }}"
  - name: Refresh certificates
    command: microk8s refresh-certs
  - name: Reboot host and wait for it to restart
    reboot:
      msg: "Reboot initiated by Ansible"
      connect_timeout: 5
      reboot_timeout: 600
      pre_reboot_delay: 0
      post_reboot_delay: 30
      test_command: whoami
  become: true