---
- name: Configure NGINX ingress controller
  block:
  - name: Get status of all microk8s addons
    command: microk8s status --format short
    register: addons_status
    changed_when: False
  - name: Enable NGINX ingress controller
    command: microk8s enable ingress
    when: '"ingress: enabled" not in addons_status.stdout'
  when: 'inventory_hostname == "k8s_node0"'
  become: true
